# This is a basic workflow to help you get started with Actions


name: Manual workflow

on: 
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "main" ]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting1
      run: |
       pwd
       cd ../../..
       ls -lart
    - name: Send greeting
      run: |
        cd ..
        sh mail.sh
        sh mail_test.sh 
